language: java
jdk:
  - oraclejdk7
addons:
  postgresql: "9.3"
before_install:
 - gem install compass
script: ant setupDB test dist
notifications:
 deploy:
  provider: releases
  user: "Ebaneck"
  password: "aboliga7"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
